"""empty message

Revision ID: 222308c6e5d4
Revises: aca7c965d568
Create Date: 2024-09-09 17:40:46.790366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222308c6e5d4'
down_revision = 'aca7c965d568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_menu', ['pid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('t_roles')
    # ### end Alembic commands ###
