"""empty message

Revision ID: 4f6cae6bbbe9
Revises: 239c8fbecd30
Create Date: 2024-09-10 08:34:34.858129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6cae6bbbe9'
down_revision = '239c8fbecd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles_menus',
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.Column('menus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menus_id'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['roles_id'], ['t_roles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_roles_menus')
    # ### end Alembic commands ###
