"""empty message

Revision ID: 958e1e0cff25
Revises: 85b203ef0f2f
Create Date: 2024-09-14 10:12:41.412558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958e1e0cff25'
down_revision = '85b203ef0f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('val', sa.String(length=255), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_attributes')
    # ### end Alembic commands ###
